let Heroes = [
  // {
  //   Name: "antimage",
  //   ID: 1,
  //   LocalizedName: "Anti-Mage",
  // },
  // {
  //   Name: "axe",
  //   ID: 2,
  //   LocalizedName: "Axe",
  // },
  // {
  //   Name: "bane",
  //   ID: 3,
  //   LocalizedName: "Bane",
  // },
  // {
  //   Name: "bloodseeker",
  //   ID: 4,
  //   LocalizedName: "Bloodseeker",
  // },
  // {
  //   Name: "crystal_maiden",
  //   ID: 5,
  //   LocalizedName: "Crystal Maiden",
  // },
  // {
  //   Name: "drow_ranger",
  //   ID: 6,
  //   LocalizedName: "Drow Ranger",
  // },
  // {
  //   Name: "earthshaker",
  //   ID: 7,
  //   LocalizedName: "Earthshaker",
  // },
  // {
  //   Name: "juggernaut",
  //   ID: 8,
  //   LocalizedName: "Juggernaut",
  // },
  // {
  //   Name: "mirana",
  //   ID: 9,
  //   LocalizedName: "Mirana",
  // },
  // {
  //   Name: "nevermore",
  //   ID: 11,
  //   LocalizedName: "Shadow Fiend",
  // },
  // {
  //   Name: "morphling",
  //   ID: 10,
  //   LocalizedName: "Morphling",
  // },
  // {
  //   Name: "phantom_lancer",
  //   ID: 12,
  //   LocalizedName: "Phantom Lancer",
  // },
  // {
  //   Name: "puck",
  //   ID: 13,
  //   LocalizedName: "Puck",
  // },
  // {
  //   Name: "pudge",
  //   ID: 14,
  //   LocalizedName: "Pudge",
  // },
  // {
  //   Name: "razor",
  //   ID: 15,
  //   LocalizedName: "Razor",
  // },
  // {
  //   Name: "sand_king",
  //   ID: 16,
  //   LocalizedName: "Sand King",
  // },
  // {
  //   Name: "storm_spirit",
  //   ID: 17,
  //   LocalizedName: "Storm Spirit",
  // },
  // {
  //   Name: "sven",
  //   ID: 18,
  //   LocalizedName: "Sven",
  // },
  // {
  //   Name: "tiny",
  //   ID: 19,
  //   LocalizedName: "Tiny",
  // },
  // {
  //   Name: "vengefulspirit",
  //   ID: 20,
  //   LocalizedName: "Vengeful Spirit",
  // },
  // {
  //   Name: "windrunner",
  //   ID: 21,
  //   LocalizedName: "Windranger",
  // },
  // {
  //   Name: "zuus",
  //   ID: 22,
  //   LocalizedName: "Zeus",
  // },
  // {
  //   Name: "kunkka",
  //   ID: 23,
  //   LocalizedName: "Kunkka",
  // },
  // {
  //   Name: "lina",
  //   ID: 25,
  //   LocalizedName: "Lina",
  // },
  // {
  //   Name: "lich",
  //   ID: 31,
  //   LocalizedName: "Lich",
  // },
  // {
  //   Name: "lion",
  //   ID: 26,
  //   LocalizedName: "Lion",
  // },
  // {
  //   Name: "shadow_shaman",
  //   ID: 27,
  //   LocalizedName: "Shadow Shaman",
  // },
  // {
  //   Name: "slardar",
  //   ID: 28,
  //   LocalizedName: "Slardar",
  // },
  // {
  //   Name: "tidehunter",
  //   ID: 29,
  //   LocalizedName: "Tidehunter",
  // },
  // {
  //   Name: "witch_doctor",
  //   ID: 30,
  //   LocalizedName: "Witch Doctor",
  // },
  // {
  //   Name: "riki",
  //   ID: 32,
  //   LocalizedName: "Riki",
  // },
  // {
  //   Name: "enigma",
  //   ID: 33,
  //   LocalizedName: "Enigma",
  // },
  // {
  //   Name: "tinker",
  //   ID: 34,
  //   LocalizedName: "Tinker",
  // },
  // {
  //   Name: "sniper",
  //   ID: 35,
  //   LocalizedName: "Sniper",
  // },
  // {
  //   Name: "necrolyte",
  //   ID: 36,
  //   LocalizedName: "Necrophos",
  // },
  // {
  //   Name: "warlock",
  //   ID: 37,
  //   LocalizedName: "Warlock",
  // },
  // {
  //   Name: "beastmaster",
  //   ID: 38,
  //   LocalizedName: "Beastmaster",
  // },
  // {
  //   Name: "queenofpain",
  //   ID: 39,
  //   LocalizedName: "Queen of Pain",
  // },
  // {
  //   Name: "venomancer",
  //   ID: 40,
  //   LocalizedName: "Venomancer",
  // },
  // {
  //   Name: "faceless_void",
  //   ID: 41,
  //   LocalizedName: "Faceless Void",
  // },
  // {
  //   Name: "skeleton_king",
  //   ID: 42,
  //   LocalizedName: "Skeleton King",
  // },
  // {
  //   Name: "death_prophet",
  //   ID: 43,
  //   LocalizedName: "Death Prophet",
  // },
  // {
  //   Name: "phantom_assassin",
  //   ID: 44,
  //   LocalizedName: "Phantom Assassin",
  // },
  // {
  //   Name: "pugna",
  //   ID: 45,
  //   LocalizedName: "Pugna",
  // },
  // {
  //   Name: "templar_assassin",
  //   ID: 46,
  //   LocalizedName: "Templar Assassin",
  // },
  // {
  //   Name: "viper",
  //   ID: 47,
  //   LocalizedName: "Viper",
  // },
  // {
  //   Name: "luna",
  //   ID: 48,
  //   LocalizedName: "Luna",
  // },
  // {
  //   Name: "dragon_knight",
  //   ID: 49,
  //   LocalizedName: "Dragon Knight",
  // },
  // {
  //   Name: "dazzle",
  //   ID: 50,
  //   LocalizedName: "Dazzle",
  // },
  // {
  //   Name: "rattletrap",
  //   ID: 51,
  //   LocalizedName: "Clockwerk",
  // },
  // {
  //   Name: "leshrac",
  //   ID: 52,
  //   LocalizedName: "Leshrac",
  // },
  // {
  //   Name: "furion",
  //   ID: 53,
  //   LocalizedName: "Nature's Prophet",
  // },
  // {
  //   Name: "life_stealer",
  //   ID: 54,
  //   LocalizedName: "Lifestealer",
  // },
  // {
  //   Name: "dark_seer",
  //   ID: 55,
  //   LocalizedName: "Dark Seer",
  // },
  // {
  //   Name: "clinkz",
  //   ID: 56,
  //   LocalizedName: "Clinkz",
  // },
  // {
  //   Name: "omniknight",
  //   ID: 57,
  //   LocalizedName: "Omniknight",
  // },
  // {
  //   Name: "enchantress",
  //   ID: 58,
  //   LocalizedName: "Enchantress",
  // },
  // {
  //   Name: "huskar",
  //   ID: 59,
  //   LocalizedName: "Huskar",
  // },
  // {
  //   Name: "night_stalker",
  //   ID: 60,
  //   LocalizedName: "Night Stalker",
  // },
  // {
  //   Name: "broodmother",
  //   ID: 61,
  //   LocalizedName: "Broodmother",
  // },
  // {
  //   Name: "bounty_hunter",
  //   ID: 62,
  //   LocalizedName: "Bounty Hunter",
  // },
  // {
  //   Name: "weaver",
  //   ID: 63,
  //   LocalizedName: "Weaver",
  // },
  // {
  //   Name: "jakiro",
  //   ID: 64,
  //   LocalizedName: "Jakiro",
  // },
  // {
  //   Name: "batrider",
  //   ID: 65,
  //   LocalizedName: "Batrider",
  // },
  // {
  //   Name: "chen",
  //   ID: 66,
  //   LocalizedName: "Chen",
  // },
  // {
  //   Name: "spectre",
  //   ID: 67,
  //   LocalizedName: "Spectre",
  // },
  // {
  //   Name: "doom_bringer",
  //   ID: 69,
  //   LocalizedName: "Doom",
  // },
  // {
  //   Name: "ancient_apparition",
  //   ID: 68,
  //   LocalizedName: "Ancient Apparition",
  // },
  // {
  //   Name: "ursa",
  //   ID: 70,
  //   LocalizedName: "Ursa",
  // },
  // {
  //   Name: "spirit_breaker",
  //   ID: 71,
  //   LocalizedName: "Spirit Breaker",
  // },
  // {
  //   Name: "gyrocopter",
  //   ID: 72,
  //   LocalizedName: "Gyrocopter",
  // },
  // {
  //   Name: "alchemist",
  //   ID: 73,
  //   LocalizedName: "Alchemist",
  // },
  // {
  //   Name: "invoker",
  //   ID: 74,
  //   LocalizedName: "Invoker",
  // },
  // {
  //   Name: "silencer",
  //   ID: 75,
  //   LocalizedName: "Silencer",
  // },
  // {
  //   Name: "obsidian_destroyer",
  //   ID: 76,
  //   LocalizedName: "Outworld Devourer",
  // },
  // {
  //   Name: "lycan",
  //   ID: 77,
  //   LocalizedName: "Lycanthrope",
  // },
  // {
  //   Name: "brewmaster",
  //   ID: 78,
  //   LocalizedName: "Brewmaster",
  // },
  // {
  //   Name: "shadow_demon",
  //   ID: 79,
  //   LocalizedName: "Shadow Demon",
  // },
  // {
  //   Name: "lone_druid",
  //   ID: 80,
  //   LocalizedName: "Lone Druid",
  // },
  // {
  //   Name: "chaos_knight",
  //   ID: 81,
  //   LocalizedName: "Chaos Knight",
  // },
  // {
  //   Name: "meepo",
  //   ID: 82,
  //   LocalizedName: "Meepo",
  // },
  // {
  //   Name: "treant",
  //   ID: 83,
  //   LocalizedName: "Treant Protector",
  // },
  // {
  //   Name: "ogre_magi",
  //   ID: 84,
  //   LocalizedName: "Ogre Magi",
  // },
  // {
  //   Name: "undying",
  //   ID: 85,
  //   LocalizedName: "Undying",
  // },
  // {
  //   Name: "rubick",
  //   ID: 86,
  //   LocalizedName: "Rubick",
  // },
  // {
  //   Name: "disruptor",
  //   ID: 87,
  //   LocalizedName: "Disruptor",
  // },
  // {
  //   Name: "nyx_assassin",
  //   ID: 88,
  //   LocalizedName: "Nyx Assassin",
  // },
  // {
  //   Name: "naga_siren",
  //   ID: 89,
  //   LocalizedName: "Naga Siren",
  // },
  // {
  //   Name: "keeper_of_the_light",
  //   ID: 90,
  //   LocalizedName: "Keeper of the Light",
  // },
  // {
  //   Name: "wisp",
  //   ID: 91,
  //   LocalizedName: "Wisp",
  // },
  // {
  //   Name: "visage",
  //   ID: 92,
  //   LocalizedName: "Visage",
  // },
  // {
  //   Name: "slark",
  //   ID: 93,
  //   LocalizedName: "Slark",
  // },
  // {
  //   Name: "medusa",
  //   ID: 94,
  //   LocalizedName: "Medusa",
  // },
  // {
  //   Name: "troll_warlord",
  //   ID: 95,
  //   LocalizedName: "Troll Warlord",
  // },
  // {
  //   Name: "centaur",
  //   ID: 96,
  //   LocalizedName: "Centaur Warrunner",
  // },
  // {
  //   Name: "magnataur",
  //   ID: 97,
  //   LocalizedName: "Magnus",
  // },
  // {
  //   Name: "shredder",
  //   ID: 98,
  //   LocalizedName: "Timbersaw",
  // },
  // {
  //   Name: "bristleback",
  //   ID: 99,
  //   LocalizedName: "Bristleback",
  // },
  // {
  //   Name: "tusk",
  //   ID: 100,
  //   LocalizedName: "Tusk",
  // },
  // {
  //   Name: "skywrath_mage",
  //   ID: 101,
  //   LocalizedName: "Skywrath Mage",
  // },
  // {
  //   Name: "abaddon",
  //   ID: 102,
  //   LocalizedName: "Abaddon",
  // },
  // {
  //   Name: "elder_titan",
  //   ID: 103,
  //   LocalizedName: "Elder Titan",
  // },
  // {
  //   Name: "legion_commander",
  //   ID: 104,
  //   LocalizedName: "Legion Commander",
  // },
  // {
  //   Name: "ember_spirit",
  //   ID: 106,
  //   LocalizedName: "Ember Spirit",
  // },
  // {
  //   Name: "earth_spirit",
  //   ID: 107,
  //   LocalizedName: "Earth Spirit",
  // },
  // {
  //   Name: "abyssal_underlord",
  //   ID: 108,
  //   LocalizedName: "Abyssal Underlord",
  // },
  // {
  //   Name: "terrorblade",
  //   ID: 109,
  //   LocalizedName: "Terrorblade",
  // },
  // {
  //   Name: "phoenix",
  //   ID: 110,
  //   LocalizedName: "Phoenix",
  // },
  // {
  //   Name: "techies",
  //   ID: 105,
  //   LocalizedName: "Techies",
  // },
  // {
  //   Name: "oracle",
  //   ID: 111,
  //   LocalizedName: "Oracle",
  // },
  // {
  //   Name: "winter_wyvern",
  //   ID: 112,
  //   LocalizedName: "Winter Wyvern",
  // },
  // //fixxx
  // {
  //   Name: "",
  //   ID: 0,
  //   LocalizedName: "",
  // },
  /////////////////////////////////////////////////////////////////////////////

  // {
  //   id: 121,
  //   image_url: "",
  //   localized_name: "Dawnbreaker",
  //   name: "dawnbreaker",
  // },
  // {
  //   id: 120,
  //   image_url: "",
  //   localized_name: "Hoodwink",
  //   name: "hoodwink",
  // },
  // {
  //   id: 119,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/119/snapfire_full.png",
  //   localized_name: "Snapfire",
  //   name: "snapfire",
  // },
  // {
  //   id: 118,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/118/void_spirit_full.png",
  //   localized_name: "Void Spirit",
  //   name: "void_spirit",
  // },
  // {
  //   id: 117,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/117/mars_full.png",
  //   localized_name: "Mars",
  //   name: "mars",
  // },
  // {
  //   id: 116,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/116/grimstroke_full.png",
  //   localized_name: "Grimstroke",
  //   name: "grimstroke",
  // },
  // {
  //   id: 115,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/115/dark_willow_full.png",
  //   localized_name: "Dark Willow",
  //   name: "dark_willow",
  // },
  // {
  //   id: 114,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/114/pangolier_full.png",
  //   localized_name: "Pangolier",
  //   name: "pangolier",
  // },
  // {
  //   id: 113,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/113/monkey_king_full.png",
  //   localized_name: "Monkey King",
  //   name: "monkey_king",
  // },
  // {
  //   id: 112,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/112/abyssal_underlord_full.png",
  //   localized_name: "Underlord",
  //   name: "abyssal_underlord",
  // },
  // {
  //   id: 111,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/111/arc_warden_full.png",
  //   localized_name: "Arc Warden",
  //   name: "arc_warden",
  // },
  // {
  //   id: 110,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/110/winter_wyvern_full.png",
  //   localized_name: "Winter Wyvern",
  //   name: "winter_wyvern",
  // },
  // {
  //   id: 109,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/109/techies_full.png",
  //   localized_name: "Techies",
  //   name: "techies",
  // },
  // {
  //   id: 108,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/108/oracle_full.png",
  //   localized_name: "Oracle",
  //   name: "oracle",
  // },
  // {
  //   id: 107,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/107/phoenix_full.png",
  //   localized_name: "Phoenix",
  //   name: "phoenix",
  // },
  // {
  //   id: 106,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/106/terrorblade_full.png",
  //   localized_name: "Terrorblade",
  //   name: "terrorblade",
  // },
  // {
  //   id: 105,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/105/earth_spirit_full.png",
  //   localized_name: "Earth Spirit",
  //   name: "earth_spirit",
  // },
  // {
  //   id: 104,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/104/ember_spirit_full.png",
  //   localized_name: "Ember Spirit",
  //   name: "ember_spirit",
  // },
  // {
  //   id: 103,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/103/legion_commander_full.png",
  //   localized_name: "Legion Commander",
  //   name: "legion_commander",
  // },
  // {
  //   id: 102,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/102/elder_titan_full.png",
  //   localized_name: "Elder Titan",
  //   name: "elder_titan",
  // },
  // {
  //   id: 101,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/101/abaddon_full.png",
  //   localized_name: "Abaddon",
  //   name: "abaddon",
  // },
  // {
  //   id: 100,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/100/skywrath_mage_full.png",
  //   localized_name: "Skywrath Mage",
  //   name: "skywrath_mage",
  // },
  // {
  //   id: 99,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/99/tusk_full.png",
  //   localized_name: "Tusk",
  //   name: "tusk",
  // },
  // {
  //   id: 98,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/98/bristleback_full.png",
  //   localized_name: "Bristleback",
  //   name: "bristleback",
  // },
  // {
  //   id: 97,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/97/shredder_full.png",
  //   localized_name: "Timbersaw",
  //   name: "shredder",
  // },
  // {
  //   id: 96,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/96/magnataur_full.png",
  //   localized_name: "Magnus",
  //   name: "magnataur",
  // },
  // {
  //   id: 95,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/95/centaur_full.png",
  //   localized_name: "Centaur Warrunner",
  //   name: "centaur",
  // },
  // {
  //   id: 94,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/94/troll_warlord_full.png",
  //   localized_name: "Troll Warlord",
  //   name: "troll_warlord",
  // },
  // {
  //   id: 93,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/93/medusa_full.png",
  //   localized_name: "Medusa",
  //   name: "medusa",
  // },
  // {
  //   id: 92,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/92/slark_full.png",
  //   localized_name: "Slark",
  //   name: "slark",
  // },
  // {
  //   id: 91,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/91/visage_full.png",
  //   localized_name: "Visage",
  //   name: "visage",
  // },
  // {
  //   id: 90,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/90/wisp_full.png",
  //   localized_name: "Io",
  //   name: "wisp",
  // },
  // {
  //   id: 89,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/89/keeper_of_the_light_full.png",
  //   localized_name: "Keeper of the Light",
  //   name: "keeper_of_the_light",
  // },
  // {
  //   id: 88,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/88/naga_siren_full.png",
  //   localized_name: "Naga Siren",
  //   name: "naga_siren",
  // },
  // {
  //   id: 87,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/87/nyx_assassin_full.png",
  //   localized_name: "Nyx Assassin",
  //   name: "nyx_assassin",
  // },
  // {
  //   id: 86,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/86/disruptor_full.png",
  //   localized_name: "Disruptor",
  //   name: "disruptor",
  // },
  // {
  //   id: 85,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/85/rubick_full.png",
  //   localized_name: "Rubick",
  //   name: "rubick",
  // },
  // {
  //   id: 84,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/84/undying_full.png",
  //   localized_name: "Undying",
  //   name: "undying",
  // },
  // {
  //   id: 83,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/83/ogre_magi_full.png",
  //   localized_name: "Ogre Magi",
  //   name: "ogre_magi",
  // },
  // {
  //   id: 82,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/82/treant_full.png",
  //   localized_name: "Treant Protector",
  //   name: "treant",
  // },
  // {
  //   id: 81,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/81/meepo_full.png",
  //   localized_name: "Meepo",
  //   name: "meepo",
  // },
  // {
  //   id: 80,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/80/chaos_knight_full.png",
  //   localized_name: "Chaos Knight",
  //   name: "chaos_knight",
  // },
  // {
  //   id: 79,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/79/lone_druid_full.png",
  //   localized_name: "Lone Druid",
  //   name: "lone_druid",
  // },
  // {
  //   id: 78,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/78/shadow_demon_full.png",
  //   localized_name: "Shadow Demon",
  //   name: "shadow_demon",
  // },
  // {
  //   id: 77,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/77/brewmaster_full.png",
  //   localized_name: "Brewmaster",
  //   name: "brewmaster",
  // },
  // {
  //   id: 76,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/76/lycan_full.png",
  //   localized_name: "Lycan",
  //   name: "lycan",
  // },
  // {
  //   id: 75,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/75/obsidian_destroyer_full.png",
  //   localized_name: "Outworld Devourer",
  //   name: "obsidian_destroyer",
  // },
  // {
  //   id: 74,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/74/silencer_full.png",
  //   localized_name: "Silencer",
  //   name: "silencer",
  // },
  // {
  //   id: 73,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/73/invoker_full.png",
  //   localized_name: "Invoker",
  //   name: "invoker",
  // },
  // {
  //   id: 72,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/72/alchemist_full.png",
  //   localized_name: "Alchemist",
  //   name: "alchemist",
  // },
  // {
  //   id: 71,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/71/gyrocopter_full.png",
  //   localized_name: "Gyrocopter",
  //   name: "gyrocopter",
  // },
  // {
  //   id: 70,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/70/spirit_breaker_full.png",
  //   localized_name: "Spirit Breaker",
  //   name: "spirit_breaker",
  // },
  // {
  //   id: 69,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/69/ursa_full.png",
  //   localized_name: "Ursa",
  //   name: "ursa",
  // },
  // {
  //   id: 68,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/68/ancient_apparition_full.png",
  //   localized_name: "Ancient Apparition",
  //   name: "ancient_apparition",
  // },
  // {
  //   id: 67,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/67/doom_bringer_full.png",
  //   localized_name: "Doom",
  //   name: "doom_bringer",
  // },
  // {
  //   id: 66,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/66/spectre_full.png",
  //   localized_name: "Spectre",
  //   name: "spectre",
  // },
  // {
  //   id: 65,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/65/chen_full.png",
  //   localized_name: "Chen",
  //   name: "chen",
  // },
  // {
  //   id: 64,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/64/batrider_full.png",
  //   localized_name: "Batrider",
  //   name: "batrider",
  // },
  // {
  //   id: 63,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/63/jakiro_full.png",
  //   localized_name: "Jakiro",
  //   name: "jakiro",
  // },
  // {
  //   id: 62,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/62/weaver_full.png",
  //   localized_name: "Weaver",
  //   name: "weaver",
  // },
  // {
  //   id: 61,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/61/bounty_hunter_full.png",
  //   localized_name: "Bounty Hunter",
  //   name: "bounty_hunter",
  // },
  // {
  //   id: 60,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/60/broodmother_full.png",
  //   localized_name: "Broodmother",
  //   name: "broodmother",
  // },
  // {
  //   id: 59,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/59/night_stalker_full.png",
  //   localized_name: "Night Stalker",
  //   name: "night_stalker",
  // },
  // {
  //   id: 58,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/58/huskar_full.png",
  //   localized_name: "Huskar",
  //   name: "huskar",
  // },
  // {
  //   id: 57,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/57/enchantress_full.png",
  //   localized_name: "Enchantress",
  //   name: "enchantress",
  // },
  // {
  //   id: 56,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/56/omniknight_full.png",
  //   localized_name: "Omniknight",
  //   name: "omniknight",
  // },
  // {
  //   id: 55,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/55/clinkz_full.png",
  //   localized_name: "Clinkz",
  //   name: "clinkz",
  // },
  // {
  //   id: 54,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/54/dark_seer_full.png",
  //   localized_name: "Dark Seer",
  //   name: "dark_seer",
  // },
  // {
  //   id: 53,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/53/life_stealer_full.png",
  //   localized_name: "Lifestealer",
  //   name: "life_stealer",
  // },
  // {
  //   id: 52,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/52/furion_full.png",
  //   localized_name: "Nature's Prophet",
  //   name: "furion",
  // },
  // {
  //   id: 51,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/51/leshrac_full.png",
  //   localized_name: "Leshrac",
  //   name: "leshrac",
  // },
  // {
  //   id: 50,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/50/rattletrap_full.png",
  //   localized_name: "Clockwerk",
  //   name: "rattletrap",
  // },
  // {
  //   id: 49,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/49/dazzle_full.png",
  //   localized_name: "Dazzle",
  //   name: "dazzle",
  // },
  // {
  //   id: 48,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/48/dragon_knight_full.png",
  //   localized_name: "Dragon Knight",
  //   name: "dragon_knight",
  // },
  // {
  //   id: 47,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/47/luna_full.png",
  //   localized_name: "Luna",
  //   name: "luna",
  // },
  // {
  //   id: 46,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/46/viper_full.png",
  //   localized_name: "Viper",
  //   name: "viper",
  // },
  // {
  //   id: 45,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/45/templar_assassin_full.png",
  //   localized_name: "Templar Assassin",
  //   name: "templar_assassin",
  // },
  // {
  //   id: 44,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/44/pugna_full.png",
  //   localized_name: "Pugna",
  //   name: "pugna",
  // },
  // {
  //   id: 43,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/43/phantom_assassin_full.png",
  //   localized_name: "Phantom Assassin",
  //   name: "phantom_assassin",
  // },
  // {
  //   id: 42,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/42/death_prophet_full.png",
  //   localized_name: "Death Prophet",
  //   name: "death_prophet",
  // },
  // {
  //   id: 41,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/41/skeleton_king_full.png",
  //   localized_name: "Wraith King",
  //   name: "skeleton_king",
  // },
  // {
  //   id: 40,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/40/faceless_void_full.png",
  //   localized_name: "Faceless Void",
  //   name: "faceless_void",
  // },
  // {
  //   id: 39,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/39/venomancer_full.png",
  //   localized_name: "Venomancer",
  //   name: "venomancer",
  // },
  // {
  //   id: 38,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/38/queenofpain_full.png",
  //   localized_name: "Queen of Pain",
  //   name: "queenofpain",
  // },
  // {
  //   id: 37,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/37/beastmaster_full.png",
  //   localized_name: "Beastmaster",
  //   name: "beastmaster",
  // },
  // {
  //   id: 36,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/36/warlock_full.png",
  //   localized_name: "Warlock",
  //   name: "warlock",
  // },
  // {
  //   id: 35,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/35/necrolyte_full.png",
  //   localized_name: "Necrophos",
  //   name: "necrolyte",
  // },
  // {
  //   id: 34,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/34/sniper_full.png",
  //   localized_name: "Sniper",
  //   name: "sniper",
  // },
  // {
  //   id: 33,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/33/tinker_full.png",
  //   localized_name: "Tinker",
  //   name: "tinker",
  // },
  // {
  //   id: 32,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/32/enigma_full.png",
  //   localized_name: "Enigma",
  //   name: "enigma",
  // },
  // {
  //   id: 31,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/31/riki_full.png",
  //   localized_name: "Riki",
  //   name: "riki",
  // },
  // {
  //   id: 30,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/30/witch_doctor_full.png",
  //   localized_name: "Witch Doctor",
  //   name: "witch_doctor",
  // },
  // {
  //   id: 29,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/29/tidehunter_full.png",
  //   localized_name: "Tidehunter",
  //   name: "tidehunter",
  // },
  // {
  //   id: 28,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/28/slardar_full.png",
  //   localized_name: "Slardar",
  //   name: "slardar",
  // },
  // {
  //   id: 27,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/27/shadow_shaman_full.png",
  //   localized_name: "Shadow Shaman",
  //   name: "shadow_shaman",
  // },
  // {
  //   id: 26,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/26/lion_full.png",
  //   localized_name: "Lion",
  //   name: "lion",
  // },
  // {
  //   id: 25,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/25/lich_full.png",
  //   localized_name: "Lich",
  //   name: "lich",
  // },
  // {
  //   id: 24,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/24/lina_full.png",
  //   localized_name: "Lina",
  //   name: "lina",
  // },
  // {
  //   id: 23,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/23/kunkka_full.png",
  //   localized_name: "Kunkka",
  //   name: "kunkka",
  // },
  // {
  //   id: 22,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/22/zuus_full.png",
  //   localized_name: "Zeus",
  //   name: "zuus",
  // },
  // {
  //   id: 21,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/21/windrunner_full.png",
  //   localized_name: "Windranger",
  //   name: "windrunner",
  // },
  // {
  //   id: 20,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/20/vengefulspirit_full.png",
  //   localized_name: "Vengeful Spirit",
  //   name: "vengefulspirit",
  // },
  // {
  //   id: 19,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/19/tiny_full.png",
  //   localized_name: "Tiny",
  //   name: "tiny",
  // },
  // {
  //   id: 18,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/18/sven_full.png",
  //   localized_name: "Sven",
  //   name: "sven",
  // },
  // {
  //   id: 17,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/17/storm_spirit_full.png",
  //   localized_name: "Storm Spirit",
  //   name: "storm_spirit",
  // },
  // {
  //   id: 16,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/16/sand_king_full.png",
  //   localized_name: "Sand King",
  //   name: "sand_king",
  // },
  // {
  //   id: 15,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/15/razor_full.png",
  //   localized_name: "Razor",
  //   name: "razor",
  // },
  // {
  //   id: 14,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/14/pudge_full.png",
  //   localized_name: "Pudge",
  //   name: "pudge",
  // },
  // {
  //   id: 13,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/13/puck_full.png",
  //   localized_name: "Puck",
  //   name: "puck",
  // },
  // {
  //   id: 12,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/12/phantom_lancer_full.png",
  //   localized_name: "Phantom Lancer",
  //   name: "phantom_lancer",
  // },
  // {
  //   id: 11,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/11/morphling_full.png",
  //   localized_name: "Morphling",
  //   name: "morphling",
  // },
  // {
  //   id: 10,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/10/nevermore_full.png",
  //   localized_name: "Shadow Fiend",
  //   name: "nevermore",
  // },
  // {
  //   id: 9,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/9/mirana_full.png",
  //   localized_name: "Mirana",
  //   name: "mirana",
  // },
  // {
  //   id: 8,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/8/juggernaut_full.png",
  //   localized_name: "Juggernaut",
  //   name: "juggernaut",
  // },
  // {
  //   id: 7,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/7/earthshaker_full.png",
  //   localized_name: "Earthshaker",
  //   name: "earthshaker",
  // },
  // {
  //   id: 6,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/6/drow_ranger_full.png",
  //   localized_name: "Drow Ranger",
  //   name: "drow_ranger",
  // },
  // {
  //   id: 5,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/5/crystal_maiden_full.png",
  //   localized_name: "Crystal Maiden",
  //   name: "crystal_maiden",
  // },
  // {
  //   id: 4,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/4/bloodseeker_full.png",
  //   localized_name: "Bloodseeker",
  //   name: "bloodseeker",
  // },
  // {
  //   id: 3,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/3/bane_full.png",
  //   localized_name: "Bane",
  //   name: "bane",
  // },
  // {
  //   id: 2,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/2/axe_full.png",
  //   localized_name: "Axe",
  //   name: "axe",
  // },
  // {
  //   id: 1,
  //   image_url:
  //     "https://cdn.pandascore.co/images/dota2/hero/image/1/antimage_full.png",
  //   localized_name: "Anti-Mage",
  //   name: "antimage",
  // },
  // {
  //   id: 0,
  //   image_url: "",
  //   localized_name: "",
  //   name: "",
  // },

  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  {
    id: 0,
    name: "",
    localized_name: "0",
    primary_attr: "0",
    attack_type: "0",
    roles: 0,
    legs: 0,
  },
  {
    id: 1,
    name: "antimage",
    localized_name: "Anti-Mage",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Nuker"],
    legs: 2,
  },
  {
    id: 2,
    name: "axe",
    localized_name: "Axe",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Durable", "Disabler", "Jungler", "Carry"],
    legs: 2,
  },
  {
    id: 3,
    name: "bane",
    localized_name: "Bane",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker", "Durable"],
    legs: 4,
  },
  {
    id: 4,
    name: "bloodseeker",
    localized_name: "Bloodseeker",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Disabler", "Jungler", "Nuker", "Initiator"],
    legs: 2,
  },
  {
    id: 5,
    name: "crystal_maiden",
    localized_name: "Crystal Maiden",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker", "Jungler"],
    legs: 2,
  },
  {
    id: 6,
    name: "drow_ranger",
    localized_name: "Drow Ranger",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Disabler", "Pusher"],
    legs: 2,
  },
  {
    id: 7,
    name: "earthshaker",
    localized_name: "Earthshaker",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Support", "Initiator", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 8,
    name: "juggernaut",
    localized_name: "Juggernaut",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Pusher", "Escape"],
    legs: 2,
  },
  {
    id: 9,
    name: "mirana",
    localized_name: "Mirana",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Support", "Escape", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 10,
    name: "morphling",
    localized_name: "Morphling",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Escape", "Durable", "Nuker", "Disabler"],
    legs: 0,
  },
  {
    id: 11,
    name: "nevermore",
    localized_name: "Shadow Fiend",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker"],
    legs: 0,
  },
  {
    id: 12,
    name: "phantom_lancer",
    localized_name: "Phantom Lancer",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Pusher", "Nuker"],
    legs: 2,
  },
  {
    id: 13,
    name: "puck",
    localized_name: "Puck",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Initiator", "Disabler", "Escape", "Nuker"],
    legs: 2,
  },
  {
    id: 14,
    name: "pudge",
    localized_name: "Pudge",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Disabler", "Initiator", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 15,
    name: "razor",
    localized_name: "Razor",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Durable", "Nuker", "Pusher"],
    legs: 0,
  },
  {
    id: 16,
    name: "sand_king",
    localized_name: "Sand King",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Disabler", "Support", "Nuker", "Escape", "Jungler"],
    legs: 6,
  },
  {
    id: 17,
    name: "storm_spirit",
    localized_name: "Storm Spirit",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Escape", "Nuker", "Initiator", "Disabler"],
    legs: 2,
  },
  {
    id: 18,
    name: "sven",
    localized_name: "Sven",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 19,
    name: "tiny",
    localized_name: "Tiny",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Nuker", "Pusher", "Initiator", "Durable", "Disabler"],
    legs: 2,
  },
  {
    id: 20,
    name: "vengefulspirit",
    localized_name: "Vengeful Spirit",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Support", "Initiator", "Disabler", "Nuker", "Escape"],
    legs: 2,
  },
  {
    id: 21,
    name: "windrunner",
    localized_name: "Windranger",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Support", "Disabler", "Escape", "Nuker"],
    legs: 2,
  },
  {
    id: 22,
    name: "zuus",
    localized_name: "Zeus",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Nuker", "Carry"],
    legs: 2,
  },
  {
    id: 23,
    name: "kunkka",
    localized_name: "Kunkka",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Support", "Disabler", "Initiator", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 25,
    name: "lina",
    localized_name: "Lina",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Carry", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 26,
    name: "lion",
    localized_name: "Lion",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker", "Initiator"],
    legs: 2,
  },
  {
    id: 27,
    name: "shadow_shaman",
    localized_name: "Shadow Shaman",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Pusher", "Disabler", "Nuker", "Initiator"],
    legs: 2,
  },
  {
    id: 28,
    name: "slardar",
    localized_name: "Slardar",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Durable", "Initiator", "Disabler", "Escape"],
    legs: 0,
  },
  {
    id: 29,
    name: "tidehunter",
    localized_name: "Tidehunter",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Durable", "Disabler", "Nuker", "Carry"],
    legs: 2,
  },
  {
    id: 30,
    name: "witch_doctor",
    localized_name: "Witch Doctor",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 31,
    name: "lich",
    localized_name: "Lich",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker"],
    legs: 2,
  },
  {
    id: 32,
    name: "riki",
    localized_name: "Riki",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Disabler"],
    legs: 2,
  },
  {
    id: 33,
    name: "enigma",
    localized_name: "Enigma",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Disabler", "Jungler", "Initiator", "Pusher"],
    legs: 0,
  },
  {
    id: 34,
    name: "tinker",
    localized_name: "Tinker",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Pusher"],
    legs: 2,
  },
  {
    id: 35,
    name: "sniper",
    localized_name: "Sniper",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker"],
    legs: 2,
  },
  {
    id: 36,
    name: "necrolyte",
    localized_name: "Necrophos",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Durable", "Disabler"],
    legs: 2,
  },
  {
    id: 37,
    name: "warlock",
    localized_name: "Warlock",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Initiator", "Disabler"],
    legs: 2,
  },
  {
    id: 38,
    name: "beastmaster",
    localized_name: "Beastmaster",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Disabler", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 39,
    name: "queenofpain",
    localized_name: "Queen of Pain",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Escape"],
    legs: 2,
  },
  {
    id: 40,
    name: "venomancer",
    localized_name: "Venomancer",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Initiator", "Pusher", "Disabler"],
    legs: 0,
  },
  {
    id: 41,
    name: "faceless_void",
    localized_name: "Faceless Void",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Initiator", "Disabler", "Escape", "Durable"],
    legs: 2,
  },
  {
    id: 42,
    name: "skeleton_king",
    localized_name: "Wraith King",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Support", "Durable", "Disabler", "Initiator"],
    legs: 2,
  },
  {
    id: 43,
    name: "death_prophet",
    localized_name: "Death Prophet",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Pusher", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 44,
    name: "phantom_assassin",
    localized_name: "Phantom Assassin",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape"],
    legs: 2,
  },
  {
    id: 45,
    name: "pugna",
    localized_name: "Pugna",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Nuker", "Pusher"],
    legs: 2,
  },
  {
    id: 46,
    name: "templar_assassin",
    localized_name: "Templar Assassin",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Escape"],
    legs: 2,
  },
  {
    id: 47,
    name: "viper",
    localized_name: "Viper",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Durable", "Initiator", "Disabler"],
    legs: 0,
  },
  {
    id: 48,
    name: "luna",
    localized_name: "Luna",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Pusher"],
    legs: 2,
  },
  {
    id: 49,
    name: "dragon_knight",
    localized_name: "Dragon Knight",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Pusher", "Durable", "Disabler", "Initiator", "Nuker"],
    legs: 2,
  },
  {
    id: 50,
    name: "dazzle",
    localized_name: "Dazzle",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 51,
    name: "rattletrap",
    localized_name: "Clockwerk",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Disabler", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 52,
    name: "leshrac",
    localized_name: "Leshrac",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Support", "Nuker", "Pusher", "Disabler"],
    legs: 4,
  },
  {
    id: 53,
    name: "furion",
    localized_name: "Nature's Prophet",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Jungler", "Pusher", "Escape", "Nuker"],
    legs: 2,
  },
  {
    id: 54,
    name: "life_stealer",
    localized_name: "Lifestealer",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Durable", "Jungler", "Escape", "Disabler"],
    legs: 2,
  },
  {
    id: 55,
    name: "dark_seer",
    localized_name: "Dark Seer",
    primary_attr: "int",
    attack_type: "Melee",
    roles: ["Initiator", "Jungler", "Escape", "Disabler"],
    legs: 2,
  },
  {
    id: 56,
    name: "clinkz",
    localized_name: "Clinkz",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Escape", "Pusher"],
    legs: 2,
  },
  {
    id: 57,
    name: "omniknight",
    localized_name: "Omniknight",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Support", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 58,
    name: "enchantress",
    localized_name: "Enchantress",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Jungler", "Pusher", "Durable", "Disabler"],
    legs: 4,
  },
  {
    id: 59,
    name: "huskar",
    localized_name: "Huskar",
    primary_attr: "str",
    attack_type: "Ranged",
    roles: ["Carry", "Durable", "Initiator"],
    legs: 2,
  },
  {
    id: 60,
    name: "night_stalker",
    localized_name: "Night Stalker",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 61,
    name: "broodmother",
    localized_name: "Broodmother",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Pusher", "Escape", "Nuker"],
    legs: 8,
  },
  {
    id: 62,
    name: "bounty_hunter",
    localized_name: "Bounty Hunter",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Escape", "Nuker"],
    legs: 2,
  },
  {
    id: 63,
    name: "weaver",
    localized_name: "Weaver",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Escape"],
    legs: 4,
  },
  {
    id: 64,
    name: "jakiro",
    localized_name: "Jakiro",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Pusher", "Disabler"],
    legs: 2,
  },
  {
    id: 65,
    name: "batrider",
    localized_name: "Batrider",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Initiator", "Jungler", "Disabler", "Escape"],
    legs: 2,
  },
  {
    id: 66,
    name: "chen",
    localized_name: "Chen",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Jungler", "Pusher"],
    legs: 2,
  },
  {
    id: 67,
    name: "spectre",
    localized_name: "Spectre",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Durable", "Escape"],
    legs: 0,
  },
  {
    id: 68,
    name: "ancient_apparition",
    localized_name: "Ancient Apparition",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 69,
    name: "doom_bringer",
    localized_name: "Doom",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 70,
    name: "ursa",
    localized_name: "Ursa",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Jungler", "Durable", "Disabler"],
    legs: 2,
  },
  {
    id: 71,
    name: "spirit_breaker",
    localized_name: "Spirit Breaker",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Initiator", "Disabler", "Durable", "Escape"],
    legs: 2,
  },
  {
    id: 72,
    name: "gyrocopter",
    localized_name: "Gyrocopter",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 73,
    name: "alchemist",
    localized_name: "Alchemist",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Support", "Durable", "Disabler", "Initiator", "Nuker"],
    legs: 2,
  },
  {
    id: 74,
    name: "invoker",
    localized_name: "Invoker",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Disabler", "Escape", "Pusher"],
    legs: 2,
  },
  {
    id: 75,
    name: "silencer",
    localized_name: "Silencer",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Support", "Disabler", "Initiator", "Nuker"],
    legs: 2,
  },
  {
    id: 76,
    name: "obsidian_destroyer",
    localized_name: "Outworld Destroyer",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Carry", "Nuker", "Disabler"],
    legs: 4,
  },
  {
    id: 77,
    name: "lycan",
    localized_name: "Lycan",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Pusher", "Jungler", "Durable", "Escape"],
    legs: 2,
  },
  {
    id: 78,
    name: "brewmaster",
    localized_name: "Brewmaster",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 79,
    name: "shadow_demon",
    localized_name: "Shadow Demon",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Initiator", "Nuker"],
    legs: 2,
  },
  {
    id: 80,
    name: "lone_druid",
    localized_name: "Lone Druid",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Pusher", "Jungler", "Durable"],
    legs: 2,
  },
  {
    id: 81,
    name: "chaos_knight",
    localized_name: "Chaos Knight",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Disabler", "Durable", "Pusher", "Initiator"],
    legs: 2,
  },
  {
    id: 82,
    name: "meepo",
    localized_name: "Meepo",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator", "Pusher"],
    legs: 2,
  },
  {
    id: 83,
    name: "treant",
    localized_name: "Treant Protector",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Support", "Initiator", "Durable", "Disabler", "Escape"],
    legs: 2,
  },
  {
    id: 84,
    name: "ogre_magi",
    localized_name: "Ogre Magi",
    primary_attr: "int",
    attack_type: "Melee",
    roles: ["Support", "Nuker", "Disabler", "Durable", "Initiator"],
    legs: 2,
  },
  {
    id: 85,
    name: "undying",
    localized_name: "Undying",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Support", "Durable", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 86,
    name: "rubick",
    localized_name: "Rubick",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 87,
    name: "disruptor",
    localized_name: "Disruptor",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker", "Initiator"],
    legs: 2,
  },
  {
    id: 88,
    name: "nyx_assassin",
    localized_name: "Nyx Assassin",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Disabler", "Nuker", "Initiator", "Escape"],
    legs: 6,
  },
  {
    id: 89,
    name: "naga_siren",
    localized_name: "Naga Siren",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Support", "Pusher", "Disabler", "Initiator", "Escape"],
    legs: 0,
  },
  {
    id: 90,
    name: "keeper_of_the_light",
    localized_name: "Keeper of the Light",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler", "Jungler"],
    legs: 2,
  },
  {
    id: 91,
    name: "wisp",
    localized_name: "Io",
    primary_attr: "str",
    attack_type: "Ranged",
    roles: ["Support", "Escape", "Nuker"],
    legs: 0,
  },
  {
    id: 92,
    name: "visage",
    localized_name: "Visage",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Durable", "Disabler", "Pusher"],
    legs: 2,
  },
  {
    id: 93,
    name: "slark",
    localized_name: "Slark",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 94,
    name: "medusa",
    localized_name: "Medusa",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Disabler", "Durable"],
    legs: 0,
  },
  {
    id: 95,
    name: "troll_warlord",
    localized_name: "Troll Warlord",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Pusher", "Disabler", "Durable"],
    legs: 2,
  },
  {
    id: 96,
    name: "centaur",
    localized_name: "Centaur Warrunner",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Durable", "Initiator", "Disabler", "Nuker", "Escape"],
    legs: 4,
  },
  {
    id: 97,
    name: "magnataur",
    localized_name: "Magnus",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Disabler", "Nuker", "Escape"],
    legs: 4,
  },
  {
    id: 98,
    name: "shredder",
    localized_name: "Timbersaw",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Nuker", "Durable", "Escape"],
    legs: 2,
  },
  {
    id: 99,
    name: "bristleback",
    localized_name: "Bristleback",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Durable", "Initiator", "Nuker"],
    legs: 2,
  },
  {
    id: 100,
    name: "tusk",
    localized_name: "Tusk",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 101,
    name: "skywrath_mage",
    localized_name: "Skywrath Mage",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 102,
    name: "abaddon",
    localized_name: "Abaddon",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Support", "Carry", "Durable"],
    legs: 2,
  },
  {
    id: 103,
    name: "elder_titan",
    localized_name: "Elder Titan",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Initiator", "Disabler", "Nuker", "Durable"],
    legs: 2,
  },
  {
    id: 104,
    name: "legion_commander",
    localized_name: "Legion Commander",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
    legs: 2,
  },
  {
    id: 105,
    name: "techies",
    localized_name: "Techies",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Nuker", "Disabler"],
    legs: 6,
  },
  {
    id: 106,
    name: "ember_spirit",
    localized_name: "Ember Spirit",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator"],
    legs: 2,
  },
  {
    id: 107,
    name: "earth_spirit",
    localized_name: "Earth Spirit",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Nuker", "Escape", "Disabler", "Initiator", "Durable"],
    legs: 2,
  },
  {
    id: 108,
    name: "abyssal_underlord",
    localized_name: "Underlord",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Support", "Nuker", "Disabler", "Durable", "Escape"],
    legs: 2,
  },
  {
    id: 109,
    name: "terrorblade",
    localized_name: "Terrorblade",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Pusher", "Nuker"],
    legs: 2,
  },
  {
    id: 110,
    name: "phoenix",
    localized_name: "Phoenix",
    primary_attr: "str",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Initiator", "Escape", "Disabler"],
    legs: 2,
  },
  {
    id: 111,
    name: "oracle",
    localized_name: "Oracle",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler", "Escape"],
    legs: 2,
  },
  {
    id: 112,
    name: "winter_wyvern",
    localized_name: "Winter Wyvern",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Disabler", "Nuker"],
    legs: 2,
  },
  {
    id: 113,
    name: "arc_warden",
    localized_name: "Arc Warden",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Carry", "Escape", "Nuker"],
    legs: 2,
  },
  {
    id: 114,
    name: "monkey_king",
    localized_name: "Monkey King",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Disabler", "Initiator"],
    legs: 2,
  },
  {
    id: 119,
    name: "dark_willow",
    localized_name: "Dark Willow",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler", "Escape"],
    legs: 2,
  },
  {
    id: 120,
    name: "pangolier",
    localized_name: "Pangolier",
    primary_attr: "agi",
    attack_type: "Melee",
    roles: ["Carry", "Nuker", "Disabler", "Durable", "Escape", "Initiator"],
    legs: 2,
  },
  {
    id: 121,
    name: "grimstroke",
    localized_name: "Grimstroke",
    primary_attr: "int",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler", "Escape"],
    legs: 2,
  },
  {
    id: 123,
    name: "hoodwink",
    localized_name: "Hoodwink",
    primary_attr: "agi",
    attack_type: "Ranged",
    roles: ["Nuker", "Escape", "Disabler"],
    legs: 2,
  },
  {
    id: 126,
    name: "void_spirit",
    localized_name: "Void Spirit",
    primary_attr: "int",
    attack_type: "Melee",
    roles: ["Carry", "Escape", "Nuker", "Disabler"],
    legs: 2,
  },
  {
    id: 128,
    name: "snapfire",
    localized_name: "Snapfire",
    primary_attr: "str",
    attack_type: "Ranged",
    roles: ["Support", "Nuker", "Disabler", "Escape"],
    legs: 2,
  },
  {
    id: 129,
    name: "mars",
    localized_name: "Mars",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Initiator", "Disabler", "Durable"],
    legs: 2,
  },
  {
    id: 135,
    name: "dawnbreaker",
    localized_name: "Dawnbreaker",
    primary_attr: "str",
    attack_type: "Melee",
    roles: ["Carry", "Durable"],
    legs: 2,
  },
];

export default Heroes;
